### ISSUE TITLE
Missing METHOD field in OpenAPI spec for Python APIs

### ISSUE THREAD

**Issue by Sohit1212** [AppThreat/atom-tools#25]
### Describe the bug
When trying to convert the code slice, generated from Python code with REST APIs, to openAPI spec, the METHOD field is missed.
In case of Python the method may not always be specified along with the API and is interpreted inside the function.
Is there a way this can be solved for Python?

### How to reproduce?
- Generate *usages.json* file for Python (Django/flask) using **atom**
- Convert *usages.json* to openapi spec using **atom-tools**
- Resultant openapi spec has path and parameters but no Method

### Example
```
{
    "info": {
        "title": "OpenAPI Specification for ",
        "version": "1.0.0"
    },
    "openapi": "3.0.1",
    "paths": {
        "/addFriend": {},
        "/addfriend/{name}": {
            "parameters": [
                {
                    "in": "path",
                    "name": "name",
                    "required": true
                }
            ]
        }
    }
}
```

**Comment by prabhu** [comment]
@cerrussell, this sounds like a feature request for atom. Please feel free to create a separate issue in that repo.

**Comment by cerrussell** [comment]
@Sohit1212 You are correct. It is much more difficult to get operation methods in Python, so that is still a work in progress. However, I have opened a feature request in atom as @prabhu suggested and will let you know when we figure something out - I have every confidence that we will, it is only determining the best strategy.

**Comment by prabhu** [comment]
@cerrussell, have added a [PR](https://github.com/AppThreat/atom/pull/133) to atom to pass HTTP methods for python flask under resolvedMethod (full code) and paramTypes (literal arguments alone).


[usages.slices.json.txt](https://github.com/AppThreat/atom-tools/files/14571030/usages.slices.json.txt)

```
{"callName":"bp.route","resolvedMethod":"bp.route(\"/create_user\", methods = [\"POST\"])","paramTypes":["bp","/create_user","[POST]"],"returnType":"","isExternal":true,"lineNumber":10,"columnNumber":2}
```
